services:
  db_services:
    image: postgres:latest
    env_file:
      - .env.compose
    ports:
      - "5432:5432"
    volumes:
      - url_shortner_data:/var/lib/postgresql/data
  app:
    depends_on:
      - db_services
    image: url_shortner:v1
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env.compose
    ports:
      - "8080:8080"
    command: uvicorn app.main:app --host 0.0.0.0 --port 8080 --reload
    volumes:
      - ./app:/app/app:rw
    develop:
      watch:
        - action: rebuild
          path: Dockerfile
        - action: rebuild
          path: requirements.txt
        - action: rebuild
          path: compose.yaml

volumes:
  url_shortner_data:
